### ISSUE TITLE
Build issue - Error reading resource 'assembly_probe.test.Resources.aspnet-log4net-workload-assy-attribute.dll' 

### ISSUE THREAD

**Issue by bgregorius** [apprenda/Log4Net-Onboarder#1]
When attempting to build this project after restoring NuGet packages we get:

Error reading resource 'assembly_probe.test.Resources.aspnet-log4net-workload-assy-attribute.dll' -- 'Could not find file 'C:\Users\JHoppesch.KROLL\Code\Log4Net-Onboarder\src\Tests\assembly-probe.test\Resources\aspnet-log4net-workload-assy-attribute.dll'.'

![build-errors](https://cloud.githubusercontent.com/assets/4182145/22665647/81801806-ec83-11e6-95ad-9a48cd6ed0c4.png)

**Comment by TetsujinOni** [comment]
Added missing build steps to `asp-log4net-workload-assy-attribute.csproj` `clean` and `build` targets.

**Comment by TetsujinOni** [comment]
Fixed by commit [3fca8fd](https://github.com/apprenda/Log4Net-Onboarder/commit/3fca8fd4869e06a189c537a9b4131930b8386eac)
