### ISSUE TITLE
Project does not build with VS 2015

### ISSUE THREAD

**Issue by mak3r** [apprenda/Log4Net-Onboarder#2]
When opening the project in VS 2015 without SQL Server Express installed, an error pops up indicating that there is a dependency on SQL Server 2012 LocalDB. 

The project aspnet-log4net-workload-no-assy-attribute is the project at issue.

The project should not be dependent on SQL Server

**Comment by TetsujinOni** [comment]
That project is a default EF ASP.Net site with some custom build tasks and targets consumed by the unit tests of the connector policy.

Please file a PR to reduce its dependencies.

**Comment by TetsujinOni** [comment]
The LocalDB dependency is removed in the upstream log4net update changes.
