### ISSUE TITLE
Documentation is needed

### ISSUE THREAD

**Issue by mak3r** [apprenda/Log4Net-Onboarder#3]
Reading the code, it appears that there are at least 2 different ways to use this bootstrapper. 
1) Set the initial log4net configuration in web.config or app.config
or 
2) Use a custom property to indicate which logging configuration file should be modified.
Are there others use cases?

The documentation does not indicate which of the two approaches are to be used with the basic instruction. Further detail is required.

In addition, the following projects within the solution need to be documented so that users understand which sample project to use and why.

- aspnet-config-attribute
- aspnet-log4net-workload-assy-attribute
- aspnet-log4net-workload-no-assy-attribute
- AspNet-NoLogging
- aspnet-webconfig-log4netconfighandler
- aspnet-webconfig-netfx4
- Wcf-AppConfig-Attribute
- Wcf-AppConfig-Explicit
- Wcf-Standalone-Attribute
- Wcf-Standalone-Explicit

In addition, the following project need to be documented so that users understand how to use the test harness. Can it be run off platform?

- Apprenda.Log4NetConnectorPolicy.Tests
- assembly-probe.test
- CustomAttributeTestTarget

**Comment by TetsujinOni** [comment]
There is no "use it this way" prescription with the log4net onboarder, as it is designed to work with whatever log4net configuration a platform-hosted workload uses.

* If log4net is configured in web.config or app.config, it will be detected and the Apprenda platform logging appender injected.
* If log4net is configured in a separate configuration file - "log4net.config" or "config.log4net" are both common use cases I've seen in the field - and the log4net configuration is loaded by using log4net's assembly attribute-based configuration mechanism, the probe code detects this case as well and injects the Apprenda platform configuration.
* If log4net is configured in a separate configuration file which is loaded directly in code, we cannot reliably detect the configuration file to inject, so we provide a fallback mechanism to explicitly specify what configuration file to inject the appender definition into using a custom property.

None of the projects in the repository are sample applications for the consumption of log4net; the samples you listed are the various combinations of log4net consumption which were needed to construct the test matrix for the Apprenda.Log4NetConnectorPolicy.Tests unit tests.

CustomAttributeTestTarget is exactly what it says in its name: A target assembly to test the assembly probe code used for discovery of the log4net configuration attribute. It is consumed by assembly-probe.test.

All of the unit tests are unit tests: intended to run in VS or from the command line locally as part of the normal development lifecycle of the bootstrap policy.
